const DEFAULT_MAPPING_TEMPLATE_LOCATION = 'mapping-templates';
const DEFAULT_ENCODING = 'utf8';
const DEFAULT_SCHEMA_FILE = 'schema.graphql';
const DEFAULT_HTTP_METHOD = 'POST';
const DEFAULT_RESOLVER_TYPE = 'UNIT';

const HTTPMessage = {
  REQUEST: 'request',
  RESPONSE: 'response',
};

const MappingTemplateType = {
  MAPPING_TEMPLATE: 'mappingTemplate',
  FUNCTION_CONFIGURATION: 'functionConfiguration',
};

const SourceType = {
  AMAZON_DYNAMODB: 'AMAZON_DYNAMODB',
  RELATIONAL_DATABASE: 'RELATIONAL_DATABASE',
  AWS_LAMBDA: 'AWS_LAMBDA',
  AMAZON_ELASTICSEARCH: 'AMAZON_ELASTICSEARCH',
  HTTP: 'HTTP',
};

export {
  DEFAULT_MAPPING_TEMPLATE_LOCATION,
  DEFAULT_ENCODING,
  DEFAULT_SCHEMA_FILE,
  DEFAULT_HTTP_METHOD,
  DEFAULT_RESOLVER_TYPE,
  HTTPMessage,
  MappingTemplateType,
  SourceType,
};
